name: SanthaniMart CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Make Maven Wrapper executable
        working-directory: backend/santhani-mart
        run: chmod +x mvnw

      - name: Build Backend
        working-directory: backend/santhani-mart
        run: ./mvnw clean test